@startuml  milestone3

|IBE|
:List offers;
:Select offer;
|#AntiqueWhite|OMS|
:Adjust InventoryRQ;
|#LightPink|Transition|
:Initiate Adjust InventoryRQ;
|Async Workflow|
:Log Request;
|#LightPink|Transition|
:Create Session ID;

|Sabre Connector|
:Start Session;
:Adjust Inventory Request;
|#LightPink|Transition|
:Create Adjust InventoryRS;
|IBE|
:Add Passenger;
|OMS|
:Create Order;
|Transition|
:Create Pnr Request;
|Sabre Connector|
:Add Passenger Request;
|IBE|
:Add Seat;
|OMS|
:Update Order;
|Transition|
:Create Pnr Request;
|Sabre Connector|
:Add Passenger Request;
@enduml