apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: sabreinventorymark-sink
  annotations:
    camel.apache.org/kamelet.support.level: Preview
    camel.apache.org/catalog.version: "1.0"
    camel.apache.org/kamelet.icon: >-
      data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'
      fill='%23000000' viewBox='0 0 32 32'
      id='icon'%3E%3Cdefs%3E%3Cstyle%3E.cls-1%7Bfill:none;%7D%3C/style%3E%3C/defs%3E%3Ctitle%3Eapplication%3C/title%3E%3Cpath
      d='M16,18H6a2,2,0,0,1-2-2V6A2,2,0,0,1,6,4H16a2,2,0,0,1,2,2V16A2,2,0,0,1,16,18ZM6,6V16H16V6Z'
      transform='translate(0 0)'/%3E%3Cpath
      d='M26,12v4H22V12h4m0-2H22a2,2,0,0,0-2,2v4a2,2,0,0,0,2,2h4a2,2,0,0,0,2-2V12a2,2,0,0,0-2-2Z'
      transform='translate(0 0)'/%3E%3Cpath
      d='M26,22v4H22V22h4m0-2H22a2,2,0,0,0-2,2v4a2,2,0,0,0,2,2h4a2,2,0,0,0,2-2V22a2,2,0,0,0-2-2Z'
      transform='translate(0 0)'/%3E%3Cpath
      d='M16,22v4H12V22h4m0-2H12a2,2,0,0,0-2,2v4a2,2,0,0,0,2,2h4a2,2,0,0,0,2-2V22a2,2,0,0,0-2-2Z'
      transform='translate(0 0)'/%3E%3Cg id='_Transparent_Rectangle_'
      data-name='&lt;Transparent Rectangle&gt;'%3E%3Crect class='cls-1'
      width='32' height='32'/%3E%3C/g%3E%3C/svg%3E
    camel.apache.org/provider: Custom
    camel.apache.org/kamelet.group: transition
    camel.apache.org/kamelet.namespace: cetai
  labels:
    camel.apache.org/kamelet.type: sink
spec:
  definition:
    title: sabre inventory marking
    description: sabre inventory marking
    required:
      - sessionurl
    type: object
    properties:
      sessionurl:
        title: Sabre Session URL
        description: Sabre Session URL
        type: string
  types:
    in:
      mediaType: ""
    out:
      mediaType: ""
  dependencies:
    - camel:jackson
    - camel:kamelet
    - camel:jaxb
    - mvn:com.cetai.kamelet.util:kamelet-util:1.0
    - mvn:com.cetai.kamelet.sabreinventory.model:sabreinventory-model:1.0
  template:
    route:
      id: route-aa58
      from:
        id: from-8520
        uri: kamelet:source
        steps:
          - unmarshal:
              id: unmarshal-752a
              json:
                id: json-b611
                library: Jackson
                unmarshalType: com.cetai.kamelet.sabreinventory.model.ProductPnrVO
                disableFeatures: FAIL_ON_IGNORED_PROPERTIES,FAIL_ON_UNKNOWN_PROPERTIES
          - process:
              id: process-ba9c
              ref: productPnrProcessor
          - to:
              id: to-53de
              description: " Call Sabre CreateSessionHttp"
              uri: http
              parameters:
                httpUri: "{{sessionurl}}"
                httpMethod: POST
          - log:
              id: log-74a7
              message: ${body}
          - unmarshal:
              id: unmarshal-30b8
              jaxb:
                id: jaxb-8c85
                contextPath: com.cetai.kamelet.sabreinventory.model.SessionCreateRS
                contextPathIsClassName: true
          - process:
              id: process-a40c
              ref: adjustInventoryProcessor
          - to:
              id: to-83cc
              uri: rest
              parameters:
                method: post
                path: /mock/adjustinventory
                bindingMode: json
                host: localhost:8090
                consumes: application/json
                produces: application/json
          - log:
              id: log-74a7
              message: ${body}
