FROM sonatype/nexus3

COPY configs/nexus.properties nexus-data/etc/nexus.properties
COPY scripts/*  scripts/
# CMD [ "chmod","+x","scripts/provision.sh" ]
# CMD [ "/bin/sh","scripts/provision.sh" ]


